server:
  port: ${API_GATEWAY_PORT:8090}
  error:
    include-message: always


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

        - id: products-direct
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**

        - id: supplier-service
          uri: lb://supplier-service
          predicates:
            - Path=/supplier-service/**
          filters:
            - StripPrefix=1

        - id: supplier-direct
          uri: lb://supplier-service
          predicates:
            - Path=/api/v1/suppliers/**

        - id: purchase-service
          uri: lb://purchase-service
          predicates:
            - Path=/purchase-service/**
          filters:
            - StripPrefix=1

        - id: purchase-direct
          uri: lb://purchase-service
          predicates:
            - Path=/api/v1/purchases/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_EUREKA:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    # Tiempos más rápidos para desarrollo local
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: ALWAYS

springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: "Purchase Service"
        url: "/purchase-service/v3/api-docs"
      - name: "Product Service"
        url: "/product-service/v3/api-docs"
      - name: "Supplier Service"
        url: "/supplier-service/v3/api-docs"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: INFO