# Perfil para desarrollo local, fuera de Docker
# Hereda de application.yml y sobreescribe lo necesario

server:
  port: ${SUPPLIER_PORT:9091}
  error:
    include-message: always

spring:
  application:
    name: supplier-service-local
  datasource:
    url: jdbc:postgresql://localhost:5434/supplier
  jpa:
    show-sql: true
  messages:
    encoding: UTF-8 # <-- FORZAR CODIFICACIÃ“N

eureka:
  client:
    enabled: false
